name: omics-thesis
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12.6
  - r-base=4.4.2
  #Py
  - numpy
  - pandas
  - scikit-learn
  - mlens
  #R
  - r-tidyverse
  - r-caret
  - r-superlearner
  - r-randomforest
  - r-e1071

  - pip
  - pip:
      - snakemake
