name: omics-thesis
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:

  - python=3.11
  - r-base=4.3

  # Python
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - mlens
  - rpy2=3.5.*
  - py-cpuinfo

  # R
  - bioconductor-limma
  - r-caret
  - r-superlearner
  - r-randomforest
  - r-e1071

  # Snakemake
  - pip
  - pip:
      - snakemake
